### PR TITLE
Don't use main area widget for data registry

### PR DESCRIPTION
**Pull request by saulshanabrook**
By using the inner widget we can more easily size it, so that the datagrid
fills up the whole area

I also was not able to get it to register with the data registry unless I made it have a non optional dependency on it. For some reason, when its optional that plugin doesn't active. Do you find the same? If so, one option would be to make the dataregistry extension a non optional dependency and tell users to install both extensions in the README.

### CODE REVIEW

**Comment by telamonian** [comment]
Yeah, it seems to have stopped registering for some reason. You've been updating the structure of the `dataregistry` project a bunch lately, right? I haven't been updating to accomodate the changes, but there's no fundamental reason it shouldn't work as an optional dependency. If it's not working, that's definitely a bug, and we should look into that.

Do you see a difference in the sizing of the visible datagrid with this PR vs without it?

**Comment by saulshanabrook** [comment]
> You've been updating the structure of the dataregistry project a bunch lately, right?

These changes don't affect this and haven't been published. The optional dependency part is likely a bug in JupyterLab. What about working around it by making this a hard dependency?

> Do you see a difference in the sizing of the visible datagrid with this PR vs without it?

Yes, on a recent version of the data registry I update the size based on the height and it works now with this change.

**Comment by telamonian** [comment]
I'm not comfortable with making it a hard dependency, since there's currently no way to ensure that both extensions get installed alongside one another, and a user won't know anything's wrong with an install until runtime. I'd rather just look into the upstream bug

**Comment by telamonian** [comment]
After a clean build, I was able to get support working again for hdf5 files and groups. However, I can't open datasets. `widgets.tsx` in `dataregistry-extension==2.2.2` expects `IRegistry` to have a `.exteneralUrl` property. However, it looks like that property was only added after the [latest `2.0.0` release of `dataregistry`](https://github.com/jupyterlab/jupyterlab-data-explorer/blob/%40jupyterlab/dataregistry%402.0.0/dataregistry/src/registry.ts).

**Comment by saulshanabrook** [comment]
> I'm not comfortable with making it a hard dependency, since there's currently no way to ensure that both extensions get installed alongside one another, and a user won't know anything's wrong with an install until runtime. I'd rather just look into the upstream bug

Sounds good!


> After a clean build, I was able to get support working again for hdf5 files and groups. However, I can't open datasets. widgets.tsx in dataregistry-extension==2.2.2 expects IRegistry to have a .exteneralUrl property. However, it looks like that property was only added after the latest 2.0.0 release of dataregistry.

OK I just updated this with the newest data registry. It seems to be working now with the optional, so this PR is good to go from my end. 
Screen Shot 2019-10-03 at 3 32 49 PM

**Comment by telamonian** [comment]
I just tested and this LGTM!

I did see a reproducible issue in data browser where an hdf5 datagrid can be rendered in a bad state:

image

but I'm 98% sure it's unrelated to this PR, so I'll open a separate issue about it on `jupyterlab/jupyterlab-data-explorer`

**Comment by saulshanabrook** [comment]
> but I'm 98% sure it's unrelated to this PR, so I'll open a separate issue about it on jupyterlab/jupyterlab-data-explorer

Thank you! Yeah I have been meaning to open an issue for this. To solve it, we should take chris's advice he gave on gitter on re-rendering the datagrid. https://gitter.im/phosphorjs/phosphor?at=5d8cbb2d6d4b2512c11a6381

**Comment by telamonian** [comment]
opened an issue for the render bug at jupyterlab/jupyterlab-data-explorer#99

**Pull request merged**
